force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>DocGenius Template</label>
    <nameField>
        <displayFormat>DG_Template-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocGenius Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/Template_Status__c.field-meta.xml
<CustomField>
    <fullName>Template_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Template Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Template_Type__c</fullName>
    <label>Template Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple Template</fullName>
            </value>
            <value>
                <fullName>CSV Template</fullName>
            </value>
            <value>
                <fullName>Google Doc Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template_Data__c/Template_Data__c.object-meta.xml
<CustomObject>
    <label>DocGenius Template Data</label>
    <nameField>
        <displayFormat>DG_Data-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocGenius Template Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Data__c/fields/CSV_Fields__c.field-meta.xml
<CustomField>
    <fullName>CSV_Fields__c</fullName>
    <label>CSV Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Data__c/fields/CSV_Filter__c.field-meta.xml
<CustomField>
    <fullName>CSV_Filter__c</fullName>
    <label>CSV Filter</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Data__c/fields/CSV_Orders__c.field-meta.xml
<CustomField>
    <fullName>CSV_Orders__c</fullName>
    <label>CSV Orders</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Data__c/fields/CSV_Query__c.field-meta.xml
<CustomField>
    <fullName>CSV_Query__c</fullName>
    <label>CSV Query</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Data__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>DocGenius Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>DocGenius Template Data</relationshipLabel>
    <relationshipName>Template_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Template_Data__c/fields/Template_Page__c.field-meta.xml
<CustomField>
    <fullName>Template_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DocGenius Template Page</label>
    <referenceTo>Template_Page__c</referenceTo>
    <relationshipLabel>DocGenius Template Data</relationshipLabel>
    <relationshipName>Template_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_Data__c/fields/Template_Value_Simple__c.field-meta.xml
<CustomField>
    <fullName>Template_Value_Simple__c</fullName>
    <label>Template Value [Simple]</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Data__c/fields/Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Type__c</fullName>
    <label>Value Type [Simple]</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Body Value</fullName>
            </value>
            <value>
                <fullName>Header Value</fullName>
            </value>
            <value>
                <fullName>Footer Value</fullName>
            </value>
            <value>
                <fullName>Watermark Value</fullName>
            </value>
            <value>
                <fullName>Extracted Mapping Keys</fullName>
            </value>
            <value>
                <fullName>Page Configurations</fullName>
                <isActive>false</isActive>
                <label>Page Configurations</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template_Page__c/Template_Page__c.object-meta.xml
<CustomObject>
    <label>DocGenius Template Page</label>
    <nameField>
        <displayFormat>DG_Page-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocGenius Template Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Page__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>DocGenius Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>DocGenius Template Pages</relationshipLabel>
    <relationshipName>Template_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CloneTemplateDataController.cls
public with sharing class CloneTemplateDataController {
    @AuraEnabled
    public static newTempleatData cloneTempData(String templateId, String templateName, String templateDescription, String jsonData){

        Map<String, String> dataMap = (Map<String, String>) JSON.deserialize(jsonData, Map<String, String>.class);

        String templateType = dataMap.get('templateType');
        String templateBody;
        String watermark;
        String header;
        String pageConfiguration;
        String footer;

        String selectedFields;
        String fieldsFilters;
        String fieldOrderBy;
        String fieldLimit;
        String testtest = 'this is test';

        newTempleatData field = new newTempleatData();
        try {
            List<Template__c> newList = new List<Template__c>();
            newList = [SELECT Id, Object_API_Name__c, Template_Type__c, Header_Text__c, Template_Name__c,Template_Status__c FROM Template__c WHERE Id =: templateId];

            List<Template_Data__c> cloneTemplateData;
            cloneTemplateData = [SELECT Id, Name, CSV_Fields__c, CSV_Filter__c, CSV_Query__c, Template__c, Template_Page__c, Google_Doc_Template_Id__c, Google_Doc_WebViewLink__c, Order_No_Simple__c, Template_Value_Simple__c, Value_Type__c ,CSV_Orders__c,CSV_Limit__c FROM Template_Data__c WHERE Template__c =: templateId];

            Template__c cloneTemp = new Template__c();
                String test = newList[0].Object_API_Name__c;
                cloneTemp.Object_API_Name__c = test;
                cloneTemp.Header_Text__c = newList[0].Header_Text__c;
                cloneTemp.Template_Name__c = templateName;
                cloneTemp.Description__c = templateDescription;
                cloneTemp.Template_Status__c = newList[0].Template_Status__c;
                cloneTemp.Template_Type__c = newList[0].Template_Type__c;
            insert cloneTemp;


            if (templateType == 'Simple Template') {
                templateBody = dataMap.get('templateBody');
                watermark = dataMap.get('watermark');
                header = dataMap.get('header');
                pageConfiguration = dataMap.get('pageConfiguration');
                footer = dataMap.get('footer');
                List<Template_Data__c> newTempDataSimpel = new List<Template_Data__c>();
                for (Template_Data__c tempDataSimpel : cloneTemplateData) {
                    Template_Data__c cloneTempData = new Template_Data__c();
                    if (templateBody == 'true') {
                        cloneTempData.CSV_Fields__c = tempDataSimpel.CSV_Fields__c;
                    }
                    if (watermark == 'true') {
                        cloneTempData.CSV_Filter__c = tempDataSimpel.CSV_Filter__c;
                    }
                    if(header == 'true'){
                        cloneTempData.CSV_Orders__c = tempDataSimpel.CSV_Orders__c;
                    }
                    if(pageConfiguration == 'true'){
                        cloneTempData.CSV_Limit__c = tempDataSimpel.CSV_Limit__c; 
                    }
                    if(footer == 'true'){
                        cloneTempData.CSV_Limit__c = tempDataSimpel.CSV_Limit__c; 
                    }
                    cloneTempData.CSV_Query__c = tempDataSimpel.CSV_Query__c;
                    cloneTempData.Template__c = cloneTemp.Id;
                    // cloneTempData.Google_Doc_Template_Id__c = tempDataSimpel.Google_Doc_Template_Id__c;
                    // cloneTempData.Google_Doc_WebViewLink__c = tempDataSimpel.Google_Doc_WebViewLink__c;
                    cloneTempData.Order_No_Simple__c = tempDataSimpel.Order_No_Simple__c;
                    cloneTempData.Template_Value_Simple__c = tempDataSimpel.Template_Value_Simple__c;
                    cloneTempData.Value_Type__c = tempDataSimpel.Value_Type__c;
                    newTempDataSimpel.add(cloneTempData);
                }
                insert newTempDataSimpel;
            }
            else if(templateType == 'CSV Template'){
                selectedFields = dataMap.get('newSelectedFields');
                fieldsFilters = dataMap.get('newFieldsFilters');
                fieldOrderBy = dataMap.get('newFieldOrderBy');
                fieldLimit = dataMap.get('newFieldLimit');
                List<Template_Data__c> newTempData = new List<Template_Data__c>();
                for (Template_Data__c tempData : cloneTemplateData) {
                    Template_Data__c cloneTempData = new Template_Data__c();
                    if (selectedFields == 'true') {
                        cloneTempData.CSV_Fields__c = tempData.CSV_Fields__c;
                    }
                    if (fieldsFilters == 'true') {
                        cloneTempData.CSV_Filter__c = tempData.CSV_Filter__c;
                    }
                    if(fieldOrderBy == 'true'){
                        cloneTempData.CSV_Orders__c = tempData.CSV_Orders__c;
                    }
                    if(fieldLimit == 'true'){
                        cloneTempData.CSV_Limit__c = tempData.CSV_Limit__c; 
                    }
                    cloneTempData.CSV_Query__c = tempData.CSV_Query__c;
                    cloneTempData.Template__c = cloneTemp.Id;
                    // cloneTempData.Google_Doc_Template_Id__c = tempData.Google_Doc_Template_Id__c;
                    // cloneTempData.Google_Doc_WebViewLink__c = tempData.Google_Doc_WebViewLink__c;
                    cloneTempData.Order_No_Simple__c = tempData.Order_No_Simple__c;
                    cloneTempData.Template_Value_Simple__c = tempData.Template_Value_Simple__c;
                    cloneTempData.Value_Type__c = tempData.Value_Type__c;
                    newTempData.add(cloneTempData);
                }
                insert newTempData;
            }
            System.debug('cloneTemp.Id'+cloneTemp.Id);
             
            field.tempId = cloneTemp.Id;
            field.tempObj = cloneTemp.Object_API_Name__c;

        } catch (Exception e) {
            System.debug('Exception'+e);
            System.debug('Exception occurred at line: ' + e.getLineNumber());
            System.debug('Exception Type: ' + e.getTypeName());
        }
        return field;
    }

    public class newTempleatData{
        @AuraEnabled public String tempId{get; set;}
        @AuraEnabled public String tempObj{get; set;}
    }

}